# Generated by Django 4.2.7 on 2023-11-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=70)),
                ('orders_num', models.BigIntegerField(default=0)),
                ('cost', models.BigIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='images/autos')),
                ('engine', models.CharField(max_length=150)),
                ('modif', models.CharField(max_length=150)),
                ('config', models.CharField(max_length=150)),
            ],
        ),
    ]
